version: '2'

services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/dist:/usr/share/nginx/html:ro
    links:
      - api

  api:
    build: "./phoenix"
    ports:
      - "4000:4000"
    volumes:
      - ./phoenix/app:/app
    links:
      - db
      - db:database

  db:
    image: mariadb:10
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql

  webpack:
    build: "./webpack"
    ports:
      - "4040:8080"
    volumes:
      - ./app/src:/app/src:ro
      - ./app/dist:/app/dist:z
